### ISSUE TITLE
Unable to set preset meeting naming scheme as Personal IDShould you be able to set n

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#87]
There seems to be no way to preset your meeting naming schemes to `Personal ID`.

You can create meeting with a personal ID naming scheme when it is set to `ask` as there is a button to do so. But Personal ID is not available as a preset naming scheme

0/5 this may be by design to prevent users from unintentionally posting their meeting ID. Please confirm desired behavior.

**Comment by jasonblais** [comment]
There is also no way to preset naming scheme to use a channel name/ID.

The two (channel name, personal ID) are currently combined in the `mattermost` schema option, and are set based on the context of the meeting (posted in a DM/GM or a public/private channel).

It does feel a bit inconsistent, but I don't feel strongly one way or another. We could break the `mattermost` naming scheme into two options - channel name or personal ID.

**Comment by jespino** [comment]
I think make sense to have the option of "Personal ID" always, but I don't see the option of "Channel Name" always, the "mattermost naming scheme" is exactly for that, use it based on the context, because the "Channel Name" is not something sensible for DMs and GMs. Actually the "Ask" option doesn't allow you to use the channel name for DMs and GMs, that option is removed from the list.

We didn't include the Personal ID meeting in the list because we wanted to reduce the number of option to a very short list, and we though that the "mattermost" option was good enough to not need the personal meeting.

**Comment by jasonblais** [comment]
Right, I remember now. I'd lean towards leaving it and we can improve if we get requests / feedback from the community.

**Comment by jespino** [comment]
@jasonblais then, we can close this as wont fix for now?
